# Generated by Django 5.1.6 on 2025-03-05 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctros',
            new_name='Doctors',
        ),
    ]
